### ISSUE TITLE
Provide method to convert device timestamps to system timestamps

### ISSUE THREAD

**Issue by Brent-A** [microsoft/Azure-Kinect-Sensor-SDK#198]
**Tasks**
* [x] 1. API Design covering Windows and Linux, as well as Live and Playback
* [x] 2. Implement simple time sync by correlating PTS with CPU time at frame receipt
* [ ] 3. Implement precision time sync by reading PTS/USB frame correlation from firmware

**API design considerations**

* Hardware PTS timer has a resolution of 90kHz and resets to zero at boot and may reset during camera on/off transitions.
* Hardware PTS may drift in respect to the host clock (we should double check this assertion, and determine the worst case drift rate for long running devices).
* Because the PTS timer resets between camera on/off cycles, a function like `k4a_device_get_systemtime_from_timestamp()` may not be appropriate, or may have to be scoped to only being valid for timestamps received since the previous call to `k4a_device_start_cameras()`, since the same device timestamp may map to multiple absolute times.
* Do we need to convert to an absolute time (with date) or accurate boot specific timer?
* Will time conversion be available for recordings? If it is boot specific like `QueryPerformanceCounter` does it really make sense? Recordings taken on Linux should presumably be able to be read on Windows and visa versa with appropriate time APIs.

**Units common to platforms**

*Windows*

* `QueryPerformanceCounter`: highest precision time available, resets on each boot of PC. 
* `FILETIME`: 100-nanosecond intervals since 1601-01-01
* `SYSTEMTIME`: 1 millisecond intervals (modern systems should report in 1ms resolution)

*Linux*

* `clock_gettime(CLOCK_MONOTONIC, …)`: Highest precision available. Resets on each boot of the PC. Subject to NTP adjustment and doesn't tick during suspsend
* `clock_gettime(CLOCK_MONOTONIC_RAW, …)`: Highest precision available. Resets on each boot of the PC. Not adjusted by NTP. Only available on kernel 2.6.28 and newer.
* `clock_gettime(CLOCK_REALTIME, …)`: 1 nanosecond intervals of PC dependent resolution as an absolute time (subject to clock adjustments)
* `time_t`: seconds since 1970-01-01

**Other discussion on common timestamping**

It looks like ros2/rcutils#43 and ziglang/zig#933 both concluded that CLOCK_MONOTINIC and QueryPerformanceCounter were appropriate units for their OS abstraction. If this forms the community consensus we may want to ensure that our APIs are aligned.

**Comment by wes-b** [comment]
Still need to : Implement precision time sync by reading PTS/USB frame correlation from firmware
